---
title: "GSE42127 Data & Descriptive Stats"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(GEOquery) 
library(tidyverse)
library(oligo)
library(magrittr)
library(limma)
```

```{r}

untar("~/Downloads/GSE42127_RAW.tar",exdir='GSE42127/CEL')

celfiles = list.files("GSE42127/CEL",
                      pattern = ".CEL.gz", full=T)

GSE42127.raw = read.ilmn(files = "~/Downloads/GSE42127_RAW.tar")

GSE42127.rma = rma(GSE42127.raw)

write.csv(GSE42127.rma, 
          "~/Downloads/GSE42127rma.csv",
          row.names = F)

GSE42127.expr = as.data.frame(t(exprs(GSE42127.rma)))

write.csv(GSE42127.expr, 
          "~/Downloads/GSE42127expr.csv",
          row.names = F)

gse = getGEO("GSE42127", GSEMatrix = T)

feature.dat = 
  gse$GSE42127_series_matrix.txt.gz@featureData@data

feature.df = feature.dat[, c("ID", "Gene Symbol")]

write.csv(feature.df, 
          "~/Downloads/GSE42127symbol.csv", 
          row.names = F)
```

```{r}
gset2 = getGEO("GSE42127", GSEMatrix=T, getGPL=F)
if (length(gset2) > 1) 
  idx <- grep("GPL570", attr(gset2, "names")) else idx <- 1
gset2 <- gset2[[idx]]

# Extract microarray expression values from NCBI
GSE42127.gset = as_tibble(t(exprs(gset2)))

clin_demo_feature2 = as_tibble(gset2@phenoData@data) %>%
  select(-c(title:data_row_count), 
         -`specimen.number:ch1`, -`spor.n:ch1`, 
         -`tissue:ch1`,
         -`time_to_progression:ch1`,
         -`progression:ch1`)

GSE42127.df = cbind(clin_demo_feature2, GSE42127.expr)

# Next, we want to append clinical information onto gene expression data
gse42127.data = clin_demo_feature 


# fetch feature data to get gene symbols
feature.dat = gse$GSE42127_series_matrix.txt.gz@featureData@data 
GSE42127.symbol = 
  feature.dat[, c("ID", "Gene Symbol", "Gene Title")]
write.csv(GSE42127.symbol, 
          "~/Downloads/GSE42127_symbol.csv")

```


```{r}
gset <- getGEO("GSE42127", GSEMatrix =TRUE, getGPL=FALSE)
if (length(gset) > 1) idx <- grep("GPL6884", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

ex <- exprs(gset)
# log2 transform
qx <- as.numeric(quantile(ex, c(0., 0.25, 0.5, 0.75, 0.99, 1.0), na.rm=T))
LogC <- (qx[5] > 100) ||
          (qx[6]-qx[1] > 50 && qx[2] > 0)
if (LogC) { ex[which(ex <= 0)] <- NaN
  ex <- log2(ex) }
dev.new(width=3+ncol(gset)/6, height=5)
par(mar=c(7,4,2,1))
title <- paste ("GSE42127", "/", annotation(gset), sep ="")
boxplot(ex, boxwex=0.7, notch=T, main=title, outline=FALSE, las=2)
dev.off()
par(mar=c(4,4,2,1))
title <- paste ("GSE42127", "/", annotation(gset), " value distribution", sep ="")
plotDensities(ex, main=title, legend=F)
ex <- na.omit(ex) # eliminate rows with NAs
plotSA(lmFit(ex), main="Mean variance trend, GSE42127")
```

```{r}

```



