---
title: "GSE14814"
output: pdf_document
date: "2025-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if(!require("BiocManager", quietly = T))
  install.packages("BiocManager")
BiocManager::install("GEOquery")
library(GEOquery)
library(tidyverse)
if(!require("BiocManager", quietly = T))
  install.packages("BiocManager")
BiocManager::install("oligo")
library(oligo)
library(limma)
```

```{r}
options(timeout = 10000)
getGEOSuppFiles("GSE14814")

# untar files
untar("GSE14814/GSE14814_RAW.tar",exdir='GSE14814/CEL')

celfiles = list.files("GSE14814/CEL",
                      pattern = ".CEL.gz", full=T)
GSE14814.raw = read.celfiles(celfiles)

# normalization 
GSE14814.rma = rma(GSE14814.raw)

write.csv(GSE14814.rma, 
          "GSE14814rma.csv",
          row.names = F)

# Get the data to be used in R
GSE14814.expr = as.data.frame(t(exprs(GSE14814.rma)))

write.csv(GSE14814.expr, 
          "GSE14814expr.csv",
          row.names = F)

```

# map probe IDs to gene symbols
```{r}
# fetch feature data to get gene symbols
gse = getGEO("GSE14814", GSEMatrix = T)

feature.dat = 
  gse$GSE14814_series_matrix.txt.gz@featureData@data

feature.df = feature.dat[, c("ID", "Gene Symbol")]

write.csv(feature.df, 
          "GSE14814symbol.csv", 
          row.names = F)

gset = getGEO("GSE14814", GSEMatrix=T, getGPL=F)
if (length(gset) > 1) 
  idx <- grep("GPL201", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

# Extract microarray expression values from NCBI
GSE14814.gset = as_tibble(t(exprs(gset)))

# Next, we want to append clinical information onto gene expression data
GSE14814.data = as_tibble(gset@phenoData@data) %>%
  select(-c(title:data_row_count),
         -`relation`)

colnames(GSE14814.data) = c("Age", "Cause of Death", "DCC Sample", "DSS Status", "DSS Survival Time", "DSS Time", "Histology", "OS Status", "OS Time", "Post Surgical Treatment", "Predominant Subtype", "Sex", "Stage", "Tissue")

# fetch feature data to get gene symbols
feature.dat = gse$GSE14814_series_matrix.txt.gz@featureData@data 
GSE14814.symbol = 
  feature.dat[, c("ID", "Gene Symbol", "Gene Title")]
write.csv(GSE14814.symbol, 
          "GSE14814_symbol.csv")

write.csv(GSE14814.data, 
          file = "GSE14814_data.csv")
```

```{r}
#Merge clinical data and expression data
GSE14814.merged = cbind(GSE14814.data, GSE14814.expr)
write.csv(GSE14814.merged, 
          "GSE14814merged.csv")
```
