---
title: "GSE37745 Data & Descriptive Stats"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if(!require("BiocManager", quietly = T))
  install.packages("BiocManager")
BiocManager::install("GEOquery")
library(GEOquery) 
library(tidyverse)
if(!require("BiocManager", quietly = T))
  install.packages("BiocManager")
BiocManager::install("oligo")
library(oligo)
library(limma)
```

```{r}
options(timeout = 10000)
getGEOSuppFiles("GSE37745")

# untar files
untar("GSE37745/GSE37745_RAW.tar",exdir='GSE37745/CEL')

celfiles = list.files("GSE37745/CEL",
                      pattern = ".CEL.gz", full=T)
GSE37745.raw = read.celfiles(celfiles)

# normalization 
GSE37745.rma = rma(GSE37745.raw)

write.csv(GSE37745.rma, 
          "GSE37745rma.csv",
          row.names = F)

# Get the data to be used in R
GSE37745.expr = as.data.frame(t(exprs(GSE37745.rma)))

write.csv(GSE37745.expr, 
          "GSE37745expr.csv",
          row.names = F)
```

# map probe IDs to gene symbols
```{r}
# fetch feature data to get gene symbols
gse = getGEO("GSE37745", GSEMatrix = T)

feature.dat = 
  gse$GSE37745_series_matrix.txt.gz@featureData@data

feature.df = feature.dat[, c("ID", "Gene Symbol")]

write.csv(feature.df, 
          "GSE37745symbol.csv", 
          row.names = F)

gset1 = getGEO("GSE37745", GSEMatrix=T, getGPL=F)
if (length(gset1) > 1) 
  idx <- grep("GPL570", attr(gset1, "names")) else idx <- 1
gset1 <- gset1[[idx]]

# Extract microarray expression values from NCBI
GSE37745.gset = as_tibble(t(exprs(gset1)))

clin_demo_feature1 = as_tibble(gset1@phenoData@data) %>%
  select(-(title:data_row_count))

GSE37745.df = cbind(clin_demo_feature1, GSE37745.expr)

# Next, we want to append clinical information onto gene expression data
gse37745.data = clin_demo_feature1 
colnames(gse37745.data) = c("Adj_Treatment", "Age", "Days_Death_Status", "Days_to_Recurrence", "Dead", "Gender", "Histology", "Performance_Status", "Recurrence", "Tumor_Stage")

# fetch feature data to get gene symbols
feature.dat = gse$GSE37745_series_matrix.txt.gz@featureData@data 
GSE37745.symbol = 
  feature.dat[, c("ID", "Gene Symbol", "Gene Title")]
write.csv(GSE37745.symbol, 
          "GSE37745_symbol.csv")

write.csv(gse37745.data, 
          file = "GSE37745_data.csv")
```

```{r}
#Descriptive Stats
sex37745 = table(GSE37745.Data$Gender)
sex37745

nrow(GSE37745.Data)

adj.chemo = table(GSE37745.Data$Adj_Treatment)
adj.chemo

histology = table(GSE37745.Data$Histology)
histology

nrow(subset(GSE37745.Data, Age >= 65))
nrow(subset(GSE37745.Data, Age < 65))

stage = table(GSE37745.Data$Tumor_Stage)
stage

smoker = table(GSE37745.Data$Performance_Status)
smoker
```

```{r}
#Merge clinical data and expression data
GSE37745merged = cbind(gse37745.data, GSE37745.expr)
write.csv(GSE37745merged, 
          "GSE37745merged.csv")
```







