---
title: "GSE47115"
output: pdf_document
date: "2025-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if(!require("BiocManager", quietly = T))
  install.packages("BiocManager")
BiocManager::install("GEOquery")
library(GEOquery)
library(tidyverse)
if(!require("BiocManager", quietly = T))
  install.packages("BiocManager")
BiocManager::install("oligo")
library(oligo)
library(limma)
```


```{r}
# get supplementary files
# Download the file manually from GEO
download.file("https://ftp.ncbi.nlm.nih.gov/geo/series/GSE47nnn/GSE47115/matrix/GSE47115_series_matrix.txt.gz",
              destfile = "GSE47115_series_matrix.txt.gz")

# Load the file
#GSE47115 <- getGEO(filename = "GSE47115_series_matrix.txt.gz")


GSE47115 = getGEO("GSE47115", GSEMatrix = T)

#expression data
GSE47115.expr = exprs(GSE47115[[1]])

#background correction
GSE47115_corrected = backgroundCorrect.matrix(GSE47115.expr, method = "normexp")

#normalization
GSE47115.normalized = normalizeBetweenArrays(GSE47115_corrected, method = "quantile")

write.csv(GSE47115.normalized, 
          file = "GSE47115_data.csv")

hist(GSE47115.expr)
hist(GSE47115_corrected)
hist(GSE47115.normalized)

#range before and after
range(GSE47115.expr)
range(GSE47115.normalized)
range(GSE47115.expr)
```

```{r}
gse = getGEO("GSE47115", GSEMatrix = T)

feature.dat = 
  gse$GSE47115_series_matrix.txt.gz@featureData@data

feature.df = feature.dat[, c("ID", "ILMN_Gene")]

write.csv(feature.df, 
          "GSE47115symbol.csv", 
          row.names = F)

gset = getGEO("GSE47115", GSEMatrix=T, getGPL=F)
if (length(gset) > 1) 
  idx <- grep("GPL570", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

GSE47115.expr = as.data.frame(t(GSE47115.normalized))

GSE47115.data = as_tibble(gset@phenoData@data) %>%
  select(-(title:data_row_count), 
         -'7th ed. tnm classification:ch1')

colnames(GSE47115.data) = c("Adjuvant Chemo", "Age", "Status (as of 6/11)", "Gender", "Intraoperative Brachtherapy", "Years Quit", "Overall Survival (as of 6/11)", "Packyear", "Smoking Status", "TNM 7th Ed. Stage")

# fetch feature data to get gene symbols
#feature.dat = gse$GSE47115_series_matrix.txt.gz@featureData@data 
#GSE47115.symbol = feature.dat[, c("ID", "Gene Symbol", "Gene Title")]
#write.csv(GSE47115.symbol, "GSE47115_symbol.csv")

write.csv(GSE47115.data, 
          file = "GSE47115_data.csv")

```


```{r}
#Merge clinical data and expression data
GSE47115merged = cbind(GSE47115.data, GSE47115.expr)
write.csv(GSE47115merged, 
          "GSE47115merged.csv")
```




