---
title: "GSE50081"
output: pdf_document
date: "2025-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if(!require("BiocManager", quietly = T))
  install.packages("BiocManager")
BiocManager::install("GEOquery")
library(GEOquery)
library(tidyverse)
if(!require("BiocManager", quietly = T))
  install.packages("BiocManager")
BiocManager::install("oligo")
library(oligo)
library(limma)
```

```{r}
options(timeout = 10000)
getGEOSuppFiles("GSE50081")

# untar files
untar("GSE50081/GSE50081_RAW.tar",exdir='GSE50081/CEL')

celfiles = list.files("GSE50081/CEL",
                      pattern = ".CEL.gz", full=T)
GSE50081.raw = read.celfiles(celfiles)

# normalization 
GSE50081.rma = rma(GSE50081.raw)

write.csv(GSE50081.rma, 
          "GSE50081rma.csv",
          row.names = F)

# Get the data to be used in R
GSE50081.expr = as.data.frame(t(exprs(GSE50081.rma)))

write.csv(GSE50081.expr, 
          "GSE50081expr.csv",
          row.names = F)

```

# map probe IDs to gene symbols
```{r}
# fetch feature data to get gene symbols

gse = getGEO("GSE50081", GSEMatrix = T)

feature.dat = 
  gse$GSE50081_series_matrix.txt.gz@featureData@data

feature.df = feature.dat[, c("ID", "Gene Symbol")]

write.csv(feature.df, 
          "GSE50081symbol.csv", 
          row.names = F)

gset = getGEO("GSE50081", GSEMatrix=T, getGPL=F)
if (length(gset) > 1) 
  idx <- grep("GPL570", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

# Extract microarray expression values from NCBI
GSE50081.gset = as_tibble(t(exprs(gset)))

# Next, we want to append clinical information onto gene expression data
GSE50081.data = as_tibble(gset@phenoData@data) %>%
  select(-c(title:data_row_count))

colnames(GSE50081.data) = c("Age", "Disease Free Survival Time", "Histology", "M-Stage", "N-Stage", "Recurrence", "Sex", "Smoking", "Stage", "Status", "Survival Time", "T-Stage")

# fetch feature data to get gene symbols
feature.dat = gse$GSE50081_series_matrix.txt.gz@featureData@data 
GSE50081.symbol = 
  feature.dat[, c("ID", "Gene Symbol", "Gene Title")]
write.csv(GSE50081.symbol, 
          "GSE50081_symbol.csv")

write.csv(GSE50081.data, 
          file = "GSE50081_data.csv")
```

```{r}
#Merge clinical data and expression data
GSE50081.merged = cbind(GSE50081.data, GSE50081.expr)
write.csv(GSE50081.merged, 
          "GSE50081merged.csv")
```
