---
title: "R Notebook"
output: html_notebook
---

# downloading data from NCBI GEO site

```{r Install GEOquery}
# Install GEOquery and manage via Bioconductor packages
if(!require("BiocManager", quietly = T))
  install.packages("BiocManager")
BiocManager::install("GEOquery")

library(GEOquery)
```

```{r get files}
getGEOSuppFiles("GSE29013")

# untar files
untar("GSE29013/GSE29013_RAW.tar",
      exdir ='GSE29013/CEL')

BiocManager::install("oligo")
library(oligo)

celfiles = list.files("GSE29013/CEL", 
                      pattern = ".CEL.gz", full=T)
GSE29013.RAW = read.celfiles(celfiles)

# normalization 
GSE29013.rma = rma(GSE29013.RAW)

# Get the data to be used in R
GSE29013.expr = as_tibble(t(exprs(GSE29013.rma)))
write.csv(GSE29013.expr, "GSE29013/GSE29013_expr.csv")
```


# map probe IDs to gene symbols
```{r}
gset = getGEO("GSE29013", GSEMatrix=T, getGPL=F)
if (length(gset) > 1) 
  idx <- grep("GPL570", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

# Extract microarray expression values from NCBI
GSE29013.gset = as_tibble(t(exprs(gset)))

clin_demo_feature = as_tibble(gset@phenoData@data) %>%
  select(-c(title:data_row_count), 
         -`specimen.number:ch1`, -`spor.n:ch1`, 
         -`tissue:ch1`,
         -`time_to_progression:ch1`,
         -`progression:ch1`)

GSE29013.df = cbind(clin_demo_feature, GSE29013.expr)

# Next, we want to append clinical information onto gene expression data
clin_demo_feature1 = clin_demo_feature %>%



# fetch feature data to get gene symbols
feature.dat = 
  gse$GSE29013_series_matrix.txt.gz@featureData@data
GSE29013.symbol = 
  feature.dat[, c("ID", "Gene Symbol", "Gene Title")]
write.csv(GSE29013.symbol, 
          "D:\\Teaching\\STAT 471 Intro to R\\GSE29013\\GSE29013_symbol.csv")

```

