---
title: "PCA"
output: pdf_document
date: "2025-02-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)   # For data manipulation
library(survival)    # For survival analysis
install.packages("survminer")
library(survminer)   # For survival visualization
install.packages("ggfortify")
library(ggfortify)   # For PCA visualization
install.packages("factoextra")
library(factoextra)
install.packages("sva")
library(sva)
library(dplyr)
```

```{r}
# Directly combine datasets by rows (subjects)
expr_pair <- rbind(GSE68465.expr, GSE14814.expr)

# Generate batch labels clearly identifying samples
batch_labels <- c(rep("GSE68465", nrow(GSE68465.expr)),
                  rep("GSE14814", nrow(GSE14814.expr)))

pca_res <- prcomp(expr_pair, scale=TRUE)
fviz_pca_ind(pca_res,
             geom = "point",
             col.ind = batch_labels,
             addEllipses = TRUE,
             legend.title = "GPL96 (Before Correction)")

```

```{r}

expr_pair_combat <- ComBat(dat = t(expr_pair), batch = batch_labels, mod = NULL)

# transpose back for PCA
expr_pair_corrected <- t(expr_pair_combat)

# PCA after correction
pca_corrected <- prcomp(expr_pair_corrected, scale=TRUE)
fviz_pca_ind(pca_corrected,
             geom = "point",
             col.ind = batch_labels,
             addEllipses = TRUE,
             legend.title = "GPL96 (Corrected)")

GPL96.data = bind_rows(GSE68465.data, GSE14814.data)

write.csv(GPL96.data, 
          "GPL96_data.csv",
          row.names = F)

GPL96.expr = as.data.frame(expr_pair_corrected)
write.csv(GPL96.expr, 
          "GPL96expr.csv",
          row.names = F)

GPL96merged = cbind(GPL96.data, GPL96.expr)
write.csv(GPL96merged, 
          "GPL96merged.csv",
          row.names = F)
```



```{r}
expr_all <- rbind(GSE29013.expr, 
                  GSE37745.expr, 
                  GSE50081.expr,
                  GSE31908.expr,
                  GSE31210.expr)

# Create batch labels for all samples
batch_labels_all <- c(rep("GSE29013", nrow(GSE29013.expr)),
                      rep("GSE37745", nrow(GSE37745.expr)),
                      rep("GSE50081", nrow(GSE50081.expr)),
                      rep("GSE31908", nrow(GSE31908.expr)),
                      rep("GSE31210", nrow(GSE31210.expr)))

library(factoextra)
pca_before <- prcomp(expr_all, scale=TRUE)
fviz_pca_ind(pca_before,
             geom = "point",
             col.ind = batch_labels_all,
             addEllipses = TRUE,
             legend.title = "GPL570 (Before Correction)")

```


```{r}
expr_all_combat <- ComBat(dat = t(expr_all), batch = batch_labels_all, mod = NULL)

# transpose back for PCA and downstream analyses
expr_all_corrected <- t(expr_all_combat)

pca_after <- prcomp(expr_all_corrected, scale=TRUE)
fviz_pca_ind(pca_after,
             geom = "point",
             col.ind = batch_labels_all,
             addEllipses = TRUE,
             legend.title = "GPL570 (Corrected)")

GPL570.expr = as.data.frame(expr_all_corrected)

GPL570.data = bind_rows(GSE29013.data, GSE37745.data, GSE50081.data, GSE31908.data, GSE31210.data)
write.csv(GPL570.data, 
          "GPL570_data.csv",
          row.names = F)

write.csv(GPL570.expr, 
          "GPL570expr.csv",
          row.names = F)

GPL570merged = cbind(GPL570.data, GPL570.expr)
write.csv(GPL570merged, 
          "GPL570merged.csv",
          row.names = F)
```

```{r}
# Remove duplicates: Keep the first occurrence of each gene symbol
GPL570.genesymbols <- annotation29013[!duplicated(annotation29013$SYMBOL), ]
write.csv(GPL570.genesymbols, 
          "GPL570symbols.csv",
          row.names = F)

GPL96.genesymbols <- annotation68465[!duplicated(annotation68465$SYMBOL), ]
write.csv(GPL96.genesymbols, 
          "GPL96symbols.csv",
          row.names = F)
```

```{r}
affygenes <- intersect(colnames(GPL570.expr), colnames(GPL96.expr))
GPL570.expr2 = GPL570.expr[, affygenes]
GPL96.expr2 = GPL96.expr[, affygenes]

expr_all <- rbind(GPL570.expr2,
                  GPL96.expr2)

# Create batch labels for all samples
batch_labels_all <- c(rep("GPL570", nrow(GPL570.expr2)),
                      rep("GPL96", nrow(GPL96.expr2)))

library(factoextra)
pca_before <- prcomp(expr_all, scale=TRUE)
fviz_pca_ind(pca_before,
             geom = "point",
             col.ind = batch_labels_all,
             addEllipses = TRUE,
             legend.title = "Affymetrix (Before Correction)")
```

```{r}
expr_all_combat <- ComBat(dat = t(expr_all), batch = batch_labels_all, mod = NULL)

# transpose back for PCA and downstream analyses
expr_all_corrected <- t(expr_all_combat)

pca_after <- prcomp(expr_all_corrected, scale=TRUE)
fviz_pca_ind(pca_after,
             geom = "point",
             col.ind = batch_labels_all,
             addEllipses = TRUE,
             legend.title = "Affymetrix (Corrected)")

affy.expr = as.data.frame(expr_all_corrected)

write.csv(affy.expr, 
          "affymetrix.expr.csv",
          row.names = F)
```

```{r}
GPL570_96.data = bind_rows(GPL570.data, GPL96.data)
GPL570_96.data <- GPL570_96.data %>%
  mutate("Adjuvant Chemo" = case_when(
    `Adjuvant Chemo` == 1 ~ "ACT",
    `Adjuvant Chemo` == 0 ~ "OBS"
  ))

GPL570_96.data$`Adjuvant Chemo` <- factor(GPL570_96.data$`Adjuvant Chemo`)
GPL570_96.data$`Adjuvant Chemo` <- relevel(GPL570_96.data$`Adjuvant Chemo`, ref = "OBS")

levels(GPL570_96.data$`Adjuvant Chemo`)

write.csv(GPL570_96.data,
          "affymetrix.data.csv",
          row.names = F)

GPL570_96.merged = cbind(GPL570_96.data, affy.expr)
write.csv(GPL570_96.merged,
          "affymetrix.merged.csv",
          row.names = F)
```

```{r}

```

